### ISSUE TITLE
Couldn't load native CL/JNI glue library. No JOCL?

### ISSUE THREAD

**Issue by AlekzNet** [hpe-cct/cct-tutorial#16]
I'm getting the following error, when I run the Neural Network tutorials:

Couln't load native CL/JNI glue library
Exception in thread "AWT-EventQueue-0" com.jogamp.common.JogampRuntimeException: JOCL is not available
	at com.jogamp.opencl.CLPlatform.initialize(CLPlatform.java:180)
	at com.jogamp.opencl.CLPlatform.initialize(CLPlatform.java:156)
	at com.jogamp.opencl.CLPlatform.listCLPlatforms(CLPlatform.java:229)
	at com.jogamp.opencl.CLPlatform.getDefault(CLPlatform.java:197)
	at cogx.platform.opencl.OpenCLPlatform.bestPlatform(OpenCLPlatform.scala:212)
	at cogx.platform.opencl.OpenCLPlatform.selectPlatform(OpenCLPlatform.scala:171)
	at cogx.platform.opencl.OpenCLPlatform.<init>(OpenCLPlatform.scala:63)
	at cogx.platform.opencl.OpenCLPlatform.<init>(OpenCLPlatform.scala:40)
	at cogx.platform.opencl.OpenCLPlatform$.apply(OpenCLPlatform.scala:244)
	at cogx.runtime.ComputeGraph.cogx$runtime$ComputeGraph$$platform$lzycompute(ComputeGraph.scala:107)
	at cogx.runtime.ComputeGraph.cogx$runtime$ComputeGraph$$platform(ComputeGraph.scala:107)
	at cogx.runtime.ComputeGraph.kernelCodeGenParams(ComputeGraph.scala:156)
	at cogx.runtime.ComputeGraph.codeGenerator$lzycompute(ComputeGraph.scala:168)
	at cogx.runtime.ComputeGraph.codeGenerator(ComputeGraph.scala:165)
	at cogx.runtime.ComputeGraph.compileCircuit(ComputeGraph.scala:184)
	at cogx.runtime.ComputeGraph.cogx$runtime$ComputeGraph$$circuit$lzycompute(ComputeGraph.scala:96)
	at cogx.runtime.ComputeGraph.cogx$runtime$ComputeGraph$$circuit(ComputeGraph.scala:91)
	at cogx.runtime.ComputeGraph.probedCircuit$lzycompute(ComputeGraph.scala:101)
	at cogx.runtime.ComputeGraph.probedCircuit(ComputeGraph.scala:101)
	at cogdebugger.DebuggerState.<init>(DebuggerState.scala:34)
	at cogdebugger.ui.CogDebugger.<init>(CogDebugger.scala:110)
	at cogdebugger.ui.CogDebugger.<init>(CogDebugger.scala:88)
	at cogdebugger.CogDebuggerApp$$anonfun$main$1.apply$mcV$sp(CogDebuggerApp.scala:127)
	at scala.swing.Swing$$anon$10.run(Swing.scala:32)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Shouldn't JOCL be included in the distribution?

**Comment by bchandle** [comment]
What operating system and architecture are you seeing this on?

JOCL is included, but the native bridge libraries it packages don't cover every OS/architecture combination. The exception you're seeing is the JOCL native loader failing to find an appropriate match for your system or failing to load a matching set of binaries. This is the full list of pre-packaged native libraries:
- android-aarch64
- android-armv6
- linux-amd64
- linux-armv6
- linux-armv6hf
- linux-i586
- macosx-universal
- solaris-amd64
- solaris-i586
- windows-amd64
- windows-i586

Of those, the only platforms CCT is reasonably well-tested on are windows-amd64, linux-amd64, and macosx-universal.

**Comment by AlekzNet** [comment]
The OS is Solaris 11.3 x86. I checked all paths, but could not find anything related. Could you please let me know the file name (or a part of it)?

**Comment by bchandle** [comment]
I had a chance to take a closer look at this today, and I'm not sure that a Solaris build of JOCL would actually help. I'm not seeing any evidence that AMD, Intel, or NVIDIA support OpenCL on Solaris. Do you have a functioning OpenCL platform on your system?

The JOCL natives should be in your Ivy cache. That's typically ~/.ivy2/cache/org.jogamp.jocl/jocl/jars. JOCL uses dynamic loading so that it isn't necessary to manually manage the java.library.path environment setting. At run time, it'll extract the native libraries from the appropriate jocl-_-natives-_ jar to a temporary directory, and then add that temporary directory to the library path.

**Comment by AlekzNet** [comment]
Hm... Looks like OpenCL (for GPU) is indeed not supported on Solaris. What means CCT can not be run on Solaris either :(  But I'm checking further, let's see what Solaris developers say...
