### ISSUE TITLE
CameraExample does not run on Linux

### ISSUE THREAD

**Issue by juliesymons** [hpe-cct/cct-tutorial#2]
This tutorial example does not execute on Linux.  The exception trace is listed below.

CameraExample calls ColorWebCam, **cogio.webcam.ColorWebCam** from the **cct-io** repository (cogio).  This in turn has dependencies on libraries from bytedeco. 

Perhaps the dependencies are not defined or resolved correctly to pull in the correct version of the bytedeco libraries that run on Linux.

Here is the stack traces from Linux.
**From Linux**

`Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnivideoInputLib in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
    at org.bytedeco.javacpp.Loader.load(Loader.java:438)
    at org.bytedeco.javacpp.Loader.load(Loader.java:381)
    at org.bytedeco.javacpp.videoInputLib.<clinit>(videoInputLib.java:10)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.bytedeco.javacpp.Loader.load(Loader.java:413)
    at org.bytedeco.javacpp.Loader.load(Loader.java:381)
    at org.bytedeco.javacpp.videoInputLib$videoInput.<clinit>(videoInputLib.java:354)
    at org.bytedeco.javacv.VideoInputFrameGrabber.start(VideoInputFrameGrabber.java:104)
    at org.bytedeco.javacv.VideoInputFrameGrabber.start(VideoInputFrameGrabber.java:101)
    at cogio.webcam.ColorWebcam$.apply(ColorWebcam.scala:100)
    at tutorial.cogio.CameraExample$$anon$1.<init>(CameraExample.scala:28)
    at tutorial.cogio.CameraExample$.<init>(CameraExample.scala:27)
    at tutorial.cogio.CameraExample$.<clinit>(CameraExample.scala)
    at tutorial.cogio.CameraExample.main(CameraExample.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.UnsatisfiedLinkError: no uuid in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
    at org.bytedeco.javacpp.Loader.load(Loader.java:429)
    ... 19 more

Process finished with exit code 1

The windows version works fine.

**Comment by AlekzNet** [comment]
I have a similar bytedeco issue on Solaris for BackgroundSubtraction, ColorMovieExample. The exception is a bit different, though:

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.bytedeco.javacpp.Loader.load(Loader.java:413)
    at org.bytedeco.javacpp.Loader.load(Loader.java:381)
    at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2597)
    at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:386)
    at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:380)
    at cogio.moviefiles.ColorMovie$.apply(ColorMovie.scala:70)
    at cogio.moviefiles.ColorMovie$.apply(ColorMovie.scala:146)
    at tutorial.cogio.BackgroundSubtraction$$anon$1.<init>(BackgroundSubtraction.scala:29)
    at tutorial.cogio.BackgroundSubtraction$.<init>(BackgroundSubtraction.scala:27)
    at tutorial.cogio.BackgroundSubtraction$.<clinit>(BackgroundSubtraction.scala)
    at tutorial.cogio.BackgroundSubtraction.main(BackgroundSubtraction.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Shutting down FFmpegFrameGrabber

Process finished with exit code 1
